import { prisma } from '../../shared/db/client.js';

/**
 * Grupos musculares e catalogo inicial de exercicios (Fase 1.3). Upsert por `slug`/`name`
 * torna o seeder idempotente — rodar `yarn db:seed` varias vezes nao duplica linhas.
 */
const MUSCLE_GROUPS = [
  { slug: 'peito', name: 'Peito' },
  { slug: 'costas', name: 'Costas' },
  { slug: 'ombros', name: 'Ombros' },
  { slug: 'biceps', name: 'Biceps' },
  { slug: 'triceps', name: 'Triceps' },
  { slug: 'antebraco', name: 'Antebraco' },
  { slug: 'quadriceps', name: 'Quadriceps' },
  { slug: 'posterior-coxa', name: 'Posterior de coxa' },
  { slug: 'gluteos', name: 'Gluteos' },
  { slug: 'panturrilha', name: 'Panturrilha' },
  { slug: 'abdomen', name: 'Abdomen' },
  { slug: 'cardio', name: 'Cardio' },
] as const;

const EXERCISES: { name: string; muscleGroup: (typeof MUSCLE_GROUPS)[number]['slug'] }[] = [
  // Peito
  { name: 'Supino reto com barra', muscleGroup: 'peito' },
  { name: 'Supino inclinado com barra', muscleGroup: 'peito' },
  { name: 'Supino declinado com barra', muscleGroup: 'peito' },
  { name: 'Supino reto com halteres', muscleGroup: 'peito' },
  { name: 'Supino inclinado com halteres', muscleGroup: 'peito' },
  { name: 'Crucifixo reto com halteres', muscleGroup: 'peito' },
  { name: 'Crucifixo inclinado com halteres', muscleGroup: 'peito' },
  { name: 'Crossover no cabo', muscleGroup: 'peito' },
  { name: 'Peck deck (voador)', muscleGroup: 'peito' },
  { name: 'Flexao de braco', muscleGroup: 'peito' },
  { name: 'Supino máquina', muscleGroup: 'peito' },
  { name: 'Paralelas (mergulho para peito)', muscleGroup: 'peito' },
  { name: 'Supino inclinado no smith', muscleGroup: 'peito' },
  { name: 'Supino reto no smith', muscleGroup: 'peito' },
  { name: 'Supino declinado com halteres', muscleGroup: 'peito' },
  { name: 'Supino inclinado máquina', muscleGroup: 'peito' },
  { name: 'Crucifixo máquina', muscleGroup: 'peito' },
  { name: 'Crucifixo declinado com halteres', muscleGroup: 'peito' },
  { name: 'Crossover polia baixa', muscleGroup: 'peito' },
  { name: 'Crossover polia alta', muscleGroup: 'peito' },
  { name: 'Flexao de braco inclinada', muscleGroup: 'peito' },
  { name: 'Flexao de braco declinada', muscleGroup: 'peito' },
  { name: 'Flexao de braco diamante', muscleGroup: 'peito' },
  { name: 'Supino com halteres pegada neutra', muscleGroup: 'peito' },
  { name: 'Svend press', muscleGroup: 'peito' },
  // Costas
  { name: 'Barra fixa (pull-up)', muscleGroup: 'costas' },
  { name: 'Puxada frontal no pulley', muscleGroup: 'costas' },
  { name: 'Puxada por tras', muscleGroup: 'costas' },
  { name: 'Remada curvada com barra', muscleGroup: 'costas' },
  { name: 'Remada unilateral com halter (serrote)', muscleGroup: 'costas' },
  { name: 'Remada cavalinho (T-bar)', muscleGroup: 'costas' },
  { name: 'Remada baixa no cabo', muscleGroup: 'costas' },
  { name: 'Levantamento terra', muscleGroup: 'costas' },
  { name: 'Levantamento terra romeno', muscleGroup: 'costas' },
  { name: 'Pullover com halter', muscleGroup: 'costas' },
  { name: 'Hiperextensao lombar', muscleGroup: 'costas' },
  { name: 'Remada máquina articulada', muscleGroup: 'costas' },
  { name: 'Barra fixa supinada (chin-up)', muscleGroup: 'costas' },
  { name: 'Barra fixa assistida (graviton)', muscleGroup: 'costas' },
  { name: 'Puxada frontal pegada supinada', muscleGroup: 'costas' },
  { name: 'Puxada com triangulo', muscleGroup: 'costas' },
  { name: 'Puxada unilateral no cabo', muscleGroup: 'costas' },
  { name: 'Pulldown com braços estendidos (cabo)', muscleGroup: 'costas' },
  { name: 'Remada curvada supinada', muscleGroup: 'costas' },
  { name: 'Remada Pendlay', muscleGroup: 'costas' },
  { name: 'Remada baixa com triangulo', muscleGroup: 'costas' },
  { name: 'Remada no smith', muscleGroup: 'costas' },
  { name: 'Remada apoiada no banco inclinado (halteres)', muscleGroup: 'costas' },
  { name: 'Remada invertida (australiana)', muscleGroup: 'costas' },
  { name: 'Remada unilateral no cabo', muscleGroup: 'costas' },
  { name: 'Remada alta máquina (pegada aberta)', muscleGroup: 'costas' },
  { name: 'Levantamento terra sumo', muscleGroup: 'costas' },
  { name: 'Levantamento terra com trap bar', muscleGroup: 'costas' },
  { name: 'Rack pull', muscleGroup: 'costas' },
  { name: 'Superman (extensao lombar no solo)', muscleGroup: 'costas' },
  // Ombros
  { name: 'Desenvolvimento militar com barra', muscleGroup: 'ombros' },
  { name: 'Desenvolvimento com halteres', muscleGroup: 'ombros' },
  { name: 'Desenvolvimento Arnold', muscleGroup: 'ombros' },
  { name: 'Elevacao lateral com halteres', muscleGroup: 'ombros' },
  { name: 'Elevacao frontal com halteres', muscleGroup: 'ombros' },
  { name: 'Elevacao lateral no cabo', muscleGroup: 'ombros' },
  { name: 'Crucifixo inverso (posterior de ombro)', muscleGroup: 'ombros' },
  { name: 'Remada alta com barra', muscleGroup: 'ombros' },
  { name: 'Encolhimento de ombros (shrug)', muscleGroup: 'ombros' },
  { name: 'Face pull no cabo', muscleGroup: 'ombros' },
  { name: 'Desenvolvimento máquina', muscleGroup: 'ombros' },
  { name: 'Desenvolvimento no smith', muscleGroup: 'ombros' },
  { name: 'Desenvolvimento por tras com barra', muscleGroup: 'ombros' },
  { name: 'Push press', muscleGroup: 'ombros' },
  { name: 'Landmine press', muscleGroup: 'ombros' },
  { name: 'Elevacao lateral máquina', muscleGroup: 'ombros' },
  { name: 'Elevacao lateral unilateral no cabo', muscleGroup: 'ombros' },
  { name: 'Elevacao lateral inclinada (deitado de lado)', muscleGroup: 'ombros' },
  { name: 'Elevacao frontal com barra', muscleGroup: 'ombros' },
  { name: 'Elevacao frontal com anilha', muscleGroup: 'ombros' },
  { name: 'Elevacao frontal no cabo', muscleGroup: 'ombros' },
  { name: 'Crucifixo inverso no peck deck', muscleGroup: 'ombros' },
  { name: 'Crucifixo inverso no cabo', muscleGroup: 'ombros' },
  { name: 'Remada alta no cabo', muscleGroup: 'ombros' },
  { name: 'Encolhimento com halteres', muscleGroup: 'ombros' },
  { name: 'Rotacao externa no cabo', muscleGroup: 'ombros' },
  { name: 'Rotacao interna no cabo', muscleGroup: 'ombros' },
  // Biceps
  { name: 'Rosca direta com barra', muscleGroup: 'biceps' },
  { name: 'Rosca direta com barra W', muscleGroup: 'biceps' },
  { name: 'Rosca alternada com halteres', muscleGroup: 'biceps' },
  { name: 'Rosca martelo', muscleGroup: 'biceps' },
  { name: 'Rosca concentrada', muscleGroup: 'biceps' },
  { name: 'Rosca scott', muscleGroup: 'biceps' },
  { name: 'Rosca no cabo', muscleGroup: 'biceps' },
  { name: 'Rosca inversa', muscleGroup: 'biceps' },
  { name: 'Rosca alternada no banco inclinado', muscleGroup: 'biceps' },
  { name: 'Rosca simultanea com halteres', muscleGroup: 'biceps' },
  { name: 'Rosca martelo no cabo (corda)', muscleGroup: 'biceps' },
  { name: 'Rosca martelo cruzada', muscleGroup: 'biceps' },
  { name: 'Rosca scott com halter', muscleGroup: 'biceps' },
  { name: 'Rosca scott máquina', muscleGroup: 'biceps' },
  { name: 'Rosca spider', muscleGroup: 'biceps' },
  { name: 'Rosca 21', muscleGroup: 'biceps' },
  { name: 'Rosca unilateral no cabo', muscleGroup: 'biceps' },
  { name: 'Rosca bayesian (cabo por tras)', muscleGroup: 'biceps' },
  { name: 'Rosca no crossover (polia alta)', muscleGroup: 'biceps' },
  { name: 'Rosca Zottman', muscleGroup: 'biceps' },
  { name: 'Rosca drag', muscleGroup: 'biceps' },
  // Triceps
  { name: 'Triceps testa com barra', muscleGroup: 'triceps' },
  { name: 'Triceps pulley (corda)', muscleGroup: 'triceps' },
  { name: 'Triceps pulley (barra reta)', muscleGroup: 'triceps' },
  { name: 'Triceps frances com halter', muscleGroup: 'triceps' },
  { name: 'Mergulho no banco (banco triceps)', muscleGroup: 'triceps' },
  { name: 'Paralelas (mergulho para triceps)', muscleGroup: 'triceps' },
  { name: 'Kickback com halter', muscleGroup: 'triceps' },
  { name: 'Supino fechado', muscleGroup: 'triceps' },
  { name: 'Triceps testa com barra W', muscleGroup: 'triceps' },
  { name: 'Triceps testa com halteres', muscleGroup: 'triceps' },
  { name: 'Triceps frances com barra', muscleGroup: 'triceps' },
  { name: 'Triceps frances no cabo (corda)', muscleGroup: 'triceps' },
  { name: 'Triceps pulley (barra V)', muscleGroup: 'triceps' },
  { name: 'Triceps pulley inverso (pegada supinada)', muscleGroup: 'triceps' },
  { name: 'Triceps unilateral no cabo', muscleGroup: 'triceps' },
  { name: 'Triceps coice no cabo', muscleGroup: 'triceps' },
  { name: 'Triceps máquina', muscleGroup: 'triceps' },
  { name: 'Mergulho máquina (dip assistido)', muscleGroup: 'triceps' },
  { name: 'JM press', muscleGroup: 'triceps' },
  { name: 'Supino fechado no smith', muscleGroup: 'triceps' },
  { name: 'Triceps cross no cabo', muscleGroup: 'triceps' },
  // Antebraco
  { name: 'Rosca de punho com barra', muscleGroup: 'antebraco' },
  { name: 'Rosca de punho inversa', muscleGroup: 'antebraco' },
  { name: 'Flexao de punho no cabo', muscleGroup: 'antebraco' },
  { name: 'Farmer walk (caminhada com halteres)', muscleGroup: 'antebraco' },
  { name: 'Rosca de punho com halter', muscleGroup: 'antebraco' },
  { name: 'Extensao de punho no cabo', muscleGroup: 'antebraco' },
  { name: 'Rolo de punho (wrist roller)', muscleGroup: 'antebraco' },
  { name: 'Pegada isometrica na barra (dead hang)', muscleGroup: 'antebraco' },
  { name: 'Pinça com anilhas (plate pinch)', muscleGroup: 'antebraco' },
  { name: 'Hand grip', muscleGroup: 'antebraco' },
  // Quadriceps
  { name: 'Agachamento livre com barra', muscleGroup: 'quadriceps' },
  { name: 'Agachamento frontal', muscleGroup: 'quadriceps' },
  { name: 'Leg press 45', muscleGroup: 'quadriceps' },
  { name: 'Cadeira extensora', muscleGroup: 'quadriceps' },
  { name: 'Agachamento no smith', muscleGroup: 'quadriceps' },
  { name: 'Afundo (passada) com halteres', muscleGroup: 'quadriceps' },
  { name: 'Agachamento búlgaro', muscleGroup: 'quadriceps' },
  { name: 'Hack squat', muscleGroup: 'quadriceps' },
  { name: 'Agachamento goblet', muscleGroup: 'quadriceps' },
  { name: 'Agachamento com halteres', muscleGroup: 'quadriceps' },
  { name: 'Agachamento livre (peso corporal)', muscleGroup: 'quadriceps' },
  { name: 'Agachamento pausado', muscleGroup: 'quadriceps' },
  { name: 'Agachamento pendulo', muscleGroup: 'quadriceps' },
  { name: 'Agachamento sissy', muscleGroup: 'quadriceps' },
  { name: 'Agachamento com salto', muscleGroup: 'quadriceps' },
  { name: 'Agachamento belt squat', muscleGroup: 'quadriceps' },
  { name: 'Leg press horizontal', muscleGroup: 'quadriceps' },
  { name: 'Leg press unilateral', muscleGroup: 'quadriceps' },
  { name: 'Cadeira extensora unilateral', muscleGroup: 'quadriceps' },
  { name: 'Afundo com barra', muscleGroup: 'quadriceps' },
  { name: 'Afundo no smith', muscleGroup: 'quadriceps' },
  { name: 'Afundo reverso', muscleGroup: 'quadriceps' },
  { name: 'Passada caminhando (walking lunge)', muscleGroup: 'quadriceps' },
  { name: 'Subida no banco (step-up)', muscleGroup: 'quadriceps' },
  { name: 'Agachamento búlgaro no smith', muscleGroup: 'quadriceps' },
  { name: 'Agachamento hack com barra', muscleGroup: 'quadriceps' },
  // Posterior de coxa
  { name: 'Mesa flexora', muscleGroup: 'posterior-coxa' },
  { name: 'Cadeira flexora', muscleGroup: 'posterior-coxa' },
  { name: 'Stiff com barra', muscleGroup: 'posterior-coxa' },
  { name: 'Stiff com halteres', muscleGroup: 'posterior-coxa' },
  { name: 'Good morning', muscleGroup: 'posterior-coxa' },
  { name: 'Flexora em pe (unilateral)', muscleGroup: 'posterior-coxa' },
  { name: 'Mesa flexora unilateral', muscleGroup: 'posterior-coxa' },
  { name: 'Stiff unilateral com halter', muscleGroup: 'posterior-coxa' },
  { name: 'Stiff no smith', muscleGroup: 'posterior-coxa' },
  { name: 'Flexao nordica', muscleGroup: 'posterior-coxa' },
  { name: 'Flexao de joelho com bola suica', muscleGroup: 'posterior-coxa' },
  { name: 'Flexao de joelho no cabo', muscleGroup: 'posterior-coxa' },
  { name: 'Glute ham raise (GHR)', muscleGroup: 'posterior-coxa' },
  // Gluteos
  { name: 'Elevacao pelvica (hip thrust)', muscleGroup: 'gluteos' },
  { name: 'Cadeira abdutora', muscleGroup: 'gluteos' },
  { name: 'Coice no cabo (glúteo)', muscleGroup: 'gluteos' },
  { name: 'Agachamento sumo com halter', muscleGroup: 'gluteos' },
  { name: 'Elevacao pelvica unilateral', muscleGroup: 'gluteos' },
  { name: 'Elevacao pelvica com halter', muscleGroup: 'gluteos' },
  { name: 'Elevacao pelvica máquina', muscleGroup: 'gluteos' },
  { name: 'Elevacao pelvica no smith', muscleGroup: 'gluteos' },
  { name: 'Ponte de gluteo (glute bridge)', muscleGroup: 'gluteos' },
  { name: 'Coice na máquina (glúteo)', muscleGroup: 'gluteos' },
  { name: 'Coice quatro apoios com caneleira', muscleGroup: 'gluteos' },
  { name: 'Abducao de quadril no cabo', muscleGroup: 'gluteos' },
  { name: 'Abducao de quadril deitado com caneleira', muscleGroup: 'gluteos' },
  { name: 'Cadeira adutora', muscleGroup: 'gluteos' },
  { name: 'Agachamento sumo com barra', muscleGroup: 'gluteos' },
  { name: 'Pull through no cabo', muscleGroup: 'gluteos' },
  { name: 'Kettlebell swing', muscleGroup: 'gluteos' },
  { name: 'Caminhada lateral com mini band', muscleGroup: 'gluteos' },
  { name: 'Hiperextensao para gluteo (45 graus)', muscleGroup: 'gluteos' },
  // Panturrilha
  { name: 'Panturrilha em pe (gemeos)', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha sentado', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha no leg press', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha no smith', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha unilateral com halter', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha em pe máquina', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha no hack', muscleGroup: 'panturrilha' },
  { name: 'Panturrilha burrinho (donkey calf raise)', muscleGroup: 'panturrilha' },
  { name: 'Elevacao de tibial (tibialis raise)', muscleGroup: 'panturrilha' },
  // Abdomen
  { name: 'Abdominal supra (crunch)', muscleGroup: 'abdomen' },
  { name: 'Abdominal infra (elevacao de pernas)', muscleGroup: 'abdomen' },
  { name: 'Prancha abdominal (plank)', muscleGroup: 'abdomen' },
  { name: 'Abdominal obliquo (bicicleta)', muscleGroup: 'abdomen' },
  { name: 'Abdominal no cabo (ajoelhado)', muscleGroup: 'abdomen' },
  { name: 'Elevacao de pernas na barra fixa', muscleGroup: 'abdomen' },
  { name: 'Rollout com roda abdominal', muscleGroup: 'abdomen' },
  { name: 'Abdominal remador', muscleGroup: 'abdomen' },
  { name: 'Abdominal canivete (V-up)', muscleGroup: 'abdomen' },
  { name: 'Abdominal declinado', muscleGroup: 'abdomen' },
  { name: 'Abdominal máquina', muscleGroup: 'abdomen' },
  { name: 'Abdominal infra no banco declinado', muscleGroup: 'abdomen' },
  { name: 'Elevacao de pernas no apoio (cadeira romana)', muscleGroup: 'abdomen' },
  { name: 'Prancha lateral', muscleGroup: 'abdomen' },
  { name: 'Prancha com toque no ombro', muscleGroup: 'abdomen' },
  { name: 'Russian twist', muscleGroup: 'abdomen' },
  { name: 'Dead bug', muscleGroup: 'abdomen' },
  { name: 'Hollow hold', muscleGroup: 'abdomen' },
  { name: 'Escalador (mountain climber)', muscleGroup: 'abdomen' },
  { name: 'Pallof press', muscleGroup: 'abdomen' },
  { name: 'Lenhador no cabo (woodchopper)', muscleGroup: 'abdomen' },
  { name: 'Abdominal obliquo com halter (flexao lateral)', muscleGroup: 'abdomen' },
  // Cardio
  { name: 'Esteira (corrida)', muscleGroup: 'cardio' },
  { name: 'Bicicleta ergometrica', muscleGroup: 'cardio' },
  { name: 'Eliptico', muscleGroup: 'cardio' },
  { name: 'Pular corda', muscleGroup: 'cardio' },
  { name: 'Remo ergometro', muscleGroup: 'cardio' },
  { name: 'Escada (stairmaster)', muscleGroup: 'cardio' },
  { name: 'Air bike (assault bike)', muscleGroup: 'cardio' },
  { name: 'Bicicleta spinning', muscleGroup: 'cardio' },
  { name: 'Esteira (caminhada inclinada)', muscleGroup: 'cardio' },
  { name: 'Corrida ao ar livre', muscleGroup: 'cardio' },
  { name: 'Caminhada', muscleGroup: 'cardio' },
  { name: 'Natacao', muscleGroup: 'cardio' },
  { name: 'Polichinelo (jumping jack)', muscleGroup: 'cardio' },
  { name: 'Burpee', muscleGroup: 'cardio' },
  { name: 'Corda naval (battle rope)', muscleGroup: 'cardio' },
  { name: 'Ski ergometro', muscleGroup: 'cardio' },
  { name: 'Empurrar treno (sled push)', muscleGroup: 'cardio' },
  { name: 'Subida em caixa (box jump)', muscleGroup: 'cardio' },
];

export async function seedExercises(): Promise<void> {
  const muscleGroups = await Promise.all(
    MUSCLE_GROUPS.map((group) =>
      prisma.muscleGroup.upsert({
        where: { slug: group.slug },
        update: { name: group.name },
        create: group,
      }),
    ),
  );

  const groupIdBySlug = new Map(muscleGroups.map((group) => [group.slug, group.id]));

  // Sequencial de proposito: mesmo racional do `main()` em index.ts (idempotencia > paralelismo aqui).
  /* eslint-disable no-restricted-syntax, no-await-in-loop */
  for (const exercise of EXERCISES) {
    const muscleGroupId = groupIdBySlug.get(exercise.muscleGroup);

    await prisma.exercise.upsert({
      where: { name: exercise.name },
      update: { muscleGroupId },
      create: { name: exercise.name, muscleGroupId },
    });
  }
  /* eslint-enable no-restricted-syntax, no-await-in-loop */
}
